
- name: update all packages
  become: yes
  hosts: kafka-hosts zookeeper-hosts
  tasks:
    - pacman:
        update_cache: yes
    - pacman:
        upgrade: yes

- name: install required packages for kafka/zookeeper hosts
  hosts: kafka-hosts zookeeper-hosts
  become: yes
  tasks:
    - pacman:
        name:
          - jdk-openjdk
          - gnu-netcat
          - wget
          - ca-certificates  
          - zip 
          - net-tools
          - vim 
          - nano 
          - tar
        state: present

- name: disable swap on kafka/zookeeper hosts
  hosts: kafka-hosts zookeeper-hosts
  become: yes
  tasks:
    - sysctl:
        name: vm.swappiness
        value: '1'
        state: present

- name: ensure all kafka/zookeeper cluster nodes have same host entries
  hosts: all
  become: yes
  tasks: 
     - blockinfile:
         path: /etc/hosts
         block: |
           192.168.1.80 pi1
           192.168.1.81 pi2
           192.168.1.82 pi3
           192.168.1.83 pi4
           192.168.1.84 pi5
           192.168.1.82 kafka1
           192.168.1.82 zookeeper1
           192.168.1.83 kafka2
           192.168.1.83 zookeeper2
           192.168.1.84 kafka3
           192.168.1.84 zookeeper3

- name: ensure kafka/zookeeper stable software is installed under /home/acas/kafka
  hosts: kafka-hosts zookeeper-hosts
  tasks:
    - unarchive:
        src: https://archive.apache.org/dist/kafka/2.4.0/kafka_2.13-2.4.0.tgz
        dest: /home/acas
        remote_src: yes
        creates: /home/acas/kafka
      register: unpacked
    - command: mv /home/acas/kafka_2.13-2.4.0 /home/acas/kafka
      when: unpacked.changed

- name: ensure zookeeper properties are installed
  hosts: zookeeper-hosts
  become: yes
  tasks:
    - file:
        path: /data/zookeeper
        owner: root
        group: root
        mode: '0750'
        state: directory
    - template: 
        src: templates/zookeeper.properties.j2
        dest: /home/acas/kafka/config/zookeeper.properties
        owner: acas
        group: acas
        mode: '0644'
      register: zookeeper_properties
 
- name: setup zookeeper systemd service
  hosts: zookeeper-hosts
  become: yes
  vars:
    KAFKA_HOME: "/home/acas/kafka"
  tasks:
    - template:
        src: templates/zookeeper.service.j2
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: '0644'
      register: zookeeper_service
    - systemd:
         daemon_reload: yes
      when: zookeeper_service.changed or zookeeper_properties.changed
    - systemd:
         enabled: yes
         state: restarted
         name: zookeeper
