
- name: run unit tests before pushing software
  hosts: localhost
  tasks: 
    - local_action: command tox
  any_errors_fatal: true

- name: setup data directories for crawl data, geolocation and other data files
  hosts: thug_hosts x86_thug_hosts
  tasks:
     - file:
         path: /home/acas/data
         state: directory
         mode: '0750'
     - file: 
         path: /data/kafkaspider
         state: directory
         owner: acas  # must be same user as will run the spider
         mode: '0750'
       become: yes

- name: key system requirements for thug software install
  gather_facts: no
  hosts: x86_thug_hosts
  become: yes
  tasks:
    - apt: 
        name: ['rsync', 'libffi-dev', 'ssdeep', 'pkg-config', 'gcc', 'graphviz', 'graphviz-dev', 'libemu-dev']
        update_cache: yes
        state: present

- name: ensure software is on thug hosts
  hosts: thug_hosts x86_thug_hosts
  tasks:
     - file: # purge existing contents since we want a clean slate (ie. not cumulative)
         path: /home/acas/src
         state: absent
     - synchronize:
         src: src
         dest: /home/acas
         rsync_opts:
           - "--exclude=.git" 
           - "--exclude=.tox"
           - "-zz"

- name: ensure pip is installed to manage python and system is up-to-date
  hosts: kafka_hosts thug_hosts 
  become: yes
  tasks:
     - pacman: name=python-pip state=present
     - pacman:
         state: present
         name:
           libffi
           ssdeep
           pkgconfig
           gcc
           graphviz
         update_cache: yes
     - pacman: upgrade=yes 

- name: ensure libemu is installed for pygraphviz
  hosts: thug_hosts
  become: yes
  tasks:
     - unarchive:
         src: software/libemu_files.tar.gz
         dest: /
         owner: root
         group: root
 
- name: ensure python3 pre-reqs are installed
  hosts: thug_hosts 
  become: yes
  tasks:
     - pip:
         executable: pip3
         requirements: /home/acas/src/requirements.txt

- name: ensure python3 pre-reqs are install
  hosts: x86_thug_hosts
  become: yes
  tasks:
     - pip:
         requirements: /home/acas/src/requirements.txt

- name: ensure thug pip3 pre-reqs are installed
  hosts: thug_hosts x86_thug_hosts
  become: yes
  tasks:
     - pip:
         executable: pip3
         name:
           - PySocks==1.7.1
           - beautifulsoup4==4.8.2
           - cchardet==2.1.5
           - cssutils==1.0.2
           - elasticsearch==7.5.1
           - html5lib==1.0.1
           - lxml==4.4.2
           - networkx==2.4
           - pefile==2019.4.18
           - pygraphviz==1.5
           - pylibemu==0.6.1
           - pymongo==3.10.1
           - python-magic==0.4.15
           - rarfile==3.1
           - requests==2.22.0
           - six==1.13.0
           - yara-python==3.11.0
           - zope.interface==4.7.1
           - cffi
           - scrapy

- name: install data files (geolite2 city db, AU seed URLs)
  hosts: thug_hosts x86_thug_hosts
  tasks:
    - unarchive:
        src: software/GeoLite2-City_20200114.tar.gz
        dest: /home/acas/data
    - copy:
        src: software/filted_au_websites.csv
        dest: /home/acas/data/filtered_au_websites.csv
        mode: '0644'

- name: thug file install
  hosts: thug_hosts
  become: yes
  tasks:
    - unarchive:
        src: software/thug-files.tar.gz
        dest: /   # will unpack into /usr/lib/python3.8/site-packages
        owner: root
        group: root
    - unarchive:
        src: software/ssdeep_files.tar.gz
        dest: /
        owner: root
        group: root

- name: ensure ld.so finds libemu
  hosts: thug_hosts
  become: yes
  tasks:
    - template:
        src: templates/local.ld.so.conf.j2
        dest: /etc/ld.so.conf.d/local.conf
        owner: root
        group: root
        mode: '0640'
      register: template_installed
    - command: /sbin/ldconfig
      when: template_installed.changed 

#  sudo ln -s /usr/lib/libboost_python38.so.1.72.0 /usr/lib/libboost_python38.so.1.71.0
- name: boost symlink is much easier than v8 deps rebuild....
  hosts: thug_hosts
  become: yes
  tasks:
    - file:
        state: link
        owner: root
        group: root
        force: yes
        src: /usr/lib/libboost_python38.so.1.72.0
        dest: /usr/lib/libboost_python38.so.1.71.0

- name: ensure /etc/thug files are installed
  hosts: thug_hosts
  become: yes
  tasks:
    - file:
        path: /etc/thug
        owner: root
        group: root
        mode: '0755'
        state: directory
    - unarchive:
        src: software/etc_thug_files.tar.gz
        dest: /etc/thug/
        owner: root
        group: root

- name: ensure daemonize binary is installed into /usr/local/bin so that we can run executables without ansible handholding
  hosts: thug_hosts
  become: yes
  tasks:
    - copy: src=software/daemonize dest=/usr/local/bin/daemonize owner=root group=root mode='0711'
