
- name: setup app data dir for geolocation and other data files
  hosts: thug-hosts
  tasks:
     - file:
         path: /home/acas/data
         state: directory
         mode: '0750'

- name: ensure software is on thug hosts
  hosts: thug-hosts
  tasks:
     - copy:
         src: src
         dest: /home/acas
         mode: '0644'
         directory_mode: '0750'

- name: ensure pip is installed to manage python 
  hosts: kafka-hosts thug-hosts
  become: yes
  tasks:
     - pacman: name=python-pip state=present
 
- name: ensure python3 pre-reqs are installed
  hosts: thug-hosts
  become: yes
  tasks:
     - pip:
         executable: pip3
         requirements: /home/acas/src/requirements.txt

- name: install data files (geolite2 city db, AU seed URLs)
  hosts: thug-hosts
  tasks:
    - unarchive:
        src: software/GeoLite2-City_20200114.tar.gz
        dest: /home/acas/data
    - copy:
        src: software/filted_au_websites.csv
        dest: /home/acas/data/filtered_au_websites.csv
        mode: '0644'
