
- name: stop kafka manager
  become: yes
  hosts: kafka_manager
  gather_facts: no
  tasks:
    - systemd: name=kafka-manager state=stopped

- name: stop kafka, then zookeeper
  become: yes
  hosts: kafka_hosts
  gather_facts: no
  tasks:
    - systemd: name=kafka state=stopped
    - systemd: name=zookeeper state=stopped 
#    - wait_for: port=2081 state=drained

- name: poweroff cluster
  become: yes
  hosts: kafka_hosts thug_hosts zookeeper_hosts x86_thug_hosts
  gather_facts: no
  tasks:
    - command: /sbin/poweroff
