
- name: stop kafka manager
  become: yes
  hosts: kafka-manager
  gather_facts: no
  tasks:
    - systemd: name=kafka-manager state=stopped

- name: stop kafka, then zookeeper
  become: yes
  hosts: kafka-hosts
  gather_facts: no
  tasks:
    - systemd: name=kafka state=stopped
    - systemd: name=zookeeper state=stopped 
#    - wait_for: port=2081 state=drained

- name: shutdown mongo
  become: yes
  hosts: mongodb-host
  gather_facts: no
  tasks:
    - systemd: name=mongodb state=stopped
#    - wait_for: port=27017 state=drained

- name: poweroff cluster
  become: yes
  hosts: kafka-hosts thug-hosts zookeeper-hosts x86-thug-hosts
  gather_facts: no
  tasks:
    - command: /sbin/poweroff
