- name: tell processes to gracefully shutdown
  hosts: thug_hosts x86_thug_hosts
  gather_facts: no
  become: yes
  tasks:
    - shell: for f in "{{ PID_ROOT }}"/pid.* "{{ SPIDER_ROOT }}"/pid.* "{{ LOWPRIV_ROOT }}"/pid.*; do cat $f; echo; done
      register: proc
    - debug: msg="{{ proc }}"
    - shell: kill -INT {{ item }}
      with_items:
        - "{{ proc.stdout_lines }}"
      register: proc2die
    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
        timeout: 120
      with_items:
        - "{{ proc.stdout_lines }}"
    - shell: kill -HUP {{ item }}
      with_items:
        - "{{ proc.stdout_lines }}"
    - find:
        paths: "{{ PID_ROOT }}"
        patterns: 'pid.*'
      register: pid_list
    - file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ pid_list }}"
